# DefaultCompilerFlags.cmake

function(SET_COMPILER_FLAGS TARGET)
    if(NOT WIN32)
        string(ASCII 27 Esc)
        set(BoldCyan "${Esc}[1;36m")
        set(ColourReset "${Esc}[m")
    endif()
    message("${BoldCyan}Building for the local machine!${ColourReset}")
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        target_compile_options(${TARGET} PRIVATE -Wall -Wno-sign-compare -march=native -O3)
    else()
        message(FATAL_ERROR "Unsupported compiler ${CMAKE_CXX_COMPILER_ID}. Only GCC is supported.")
    endif()
endfunction()